观察我设立的电力数据npz数据集里面是什么格式

In [4]:
import numpy as np

data = np.load("electricityLondon/electricityLondon.npz")

print(data.files)

['x', 'y', 'x_offsets', 'y_offsets']


In [6]:
for key in data.files:
    arr = data[key]
    print(f"Key: {key}")
    print(f"  Shape: {arr.shape}")
    print(f"  Dtype: {arr.dtype}")
    print("-" * 40)

Key: x
  Shape: (8761, 12, 68, 3)
  Dtype: float64
----------------------------------------
Key: y
  Shape: (8761, 12, 68, 1)
  Dtype: float64
----------------------------------------
Key: x_offsets
  Shape: (12, 1)
  Dtype: int64
----------------------------------------
Key: y_offsets
  Shape: (12, 1)
  Dtype: int64
----------------------------------------


## 看一下x

In [7]:
key = data.files[0]
arr = data[key]

print(arr[0])          # 第一个样本
print(arr[0].shape)    # 再确认一次维度

[[[3.6438000e+01 0.0000000e+00 0.0000000e+00]
  [1.4300000e+01 0.0000000e+00 0.0000000e+00]
  [5.2250000e+01 0.0000000e+00 0.0000000e+00]
  ...
  [2.6000000e+01 0.0000000e+00 0.0000000e+00]
  [1.3500000e+02 0.0000000e+00 0.0000000e+00]
  [1.6822430e+02 0.0000000e+00 0.0000000e+00]]

 [[7.0750000e+01 4.1666670e-02 0.0000000e+00]
  [2.7300000e+01 4.1666670e-02 0.0000000e+00]
  [1.0625000e+02 4.1666670e-02 0.0000000e+00]
  ...
  [5.1000000e+01 4.1666670e-02 0.0000000e+00]
  [2.6500000e+02 4.1666670e-02 0.0000000e+00]
  [3.3644860e+02 4.1666670e-02 0.0000000e+00]]

 [[7.4312000e+01 8.3333330e-02 0.0000000e+00]
  [2.5700000e+01 8.3333330e-02 0.0000000e+00]
  [1.0425000e+02 8.3333330e-02 0.0000000e+00]
  ...
  [5.0000000e+01 8.3333330e-02 0.0000000e+00]
  [2.7200000e+02 8.3333330e-02 0.0000000e+00]
  [3.3644860e+02 8.3333330e-02 0.0000000e+00]]

 ...

 [[9.8938000e+01 3.7500000e-01 0.0000000e+00]
  [2.6100000e+01 3.7500000e-01 0.0000000e+00]
  [1.3175000e+02 3.7500000e-01 0.0000000e+00]
  ..

## 看一下y

In [9]:
key = data.files[1]
arr = data[key]

print(arr[0])          # 第一个样本
print(arr[0].shape)    # 再确认一次维度

[[[1.019380e+02]
  [4.150000e+01]
  [1.365000e+02]
  [2.675510e+01]
  [4.840000e+02]
  [7.492000e-01]
  [7.450000e+02]
  [7.475000e+01]
  [1.699140e+02]
  [2.936000e+02]
  [3.503673e+02]
  [7.580000e+01]
  [4.129590e+01]
  [1.604080e+01]
  [3.192857e+02]
  [5.260000e+01]
  [1.397000e+02]
  [1.667000e+02]
  [2.708000e+02]
  [7.940000e+01]
  [1.350000e+01]
  [3.261220e+01]
  [4.860710e+01]
  [5.750000e+01]
  [4.030867e+02]
  [2.347000e+02]
  [4.940000e+01]
  [3.347844e+02]
  [1.825306e+02]
  [1.886990e+01]
  [5.612760e+01]
  [1.582000e+02]
  [3.880000e+01]
  [3.300000e+01]
  [4.384082e+02]
  [2.521430e+01]
  [9.150000e+01]
  [4.370000e+01]
  [4.700000e+01]
  [1.441224e+02]
  [3.000000e+01]
  [1.500000e+01]
  [1.724567e+02]
  [1.310000e+01]
  [1.735710e+01]
  [3.632000e+02]
  [1.170000e+01]
  [1.062041e+02]
  [6.810000e+01]
  [3.291070e+01]
  [2.054960e+01]
  [1.749974e+02]
  [2.435000e+02]
  [1.130000e+01]
  [1.961000e+02]
  [5.080000e+01]
  [1.171000e+02]
  [6.660000e+01]
  [1.606000e+0