观察原本的npz数据集里面是什么格式

## 观察test

In [1]:
import numpy as np

data = np.load("PEMS08/test.npz")

print(data.files)

['x', 'y', 'x_offsets', 'y_offsets']


In [2]:
for key in data.files:
    arr = data[key]
    print(f"Key: {key}")
    print(f"  Shape: {arr.shape}")
    print(f"  Dtype: {arr.dtype}")
    print("-" * 40)

Key: x
  Shape: (3567, 12, 170, 3)
  Dtype: float64
----------------------------------------
Key: y
  Shape: (3567, 12, 170, 1)
  Dtype: float64
----------------------------------------
Key: x_offsets
  Shape: (12, 1)
  Dtype: int64
----------------------------------------
Key: y_offsets
  Shape: (12, 1)
  Dtype: int64
----------------------------------------


In [3]:
key = data.files[0]
arr = data[key]

print(arr[0])          # 第一个样本
print(arr[0].shape)    # 再确认一次维度

[[[352.           0.53472222   0.        ]
  [452.           0.53472222   0.        ]
  [314.           0.53472222   0.        ]
  ...
  [286.           0.53472222   0.        ]
  [421.           0.53472222   0.        ]
  [ 53.           0.53472222   0.        ]]

 [[335.           0.53819444   0.        ]
  [423.           0.53819444   0.        ]
  [384.           0.53819444   0.        ]
  ...
  [330.           0.53819444   0.        ]
  [419.           0.53819444   0.        ]
  [ 40.           0.53819444   0.        ]]

 [[432.           0.54166667   0.        ]
  [502.           0.54166667   0.        ]
  [325.           0.54166667   0.        ]
  ...
  [318.           0.54166667   0.        ]
  [401.           0.54166667   0.        ]
  [ 46.           0.54166667   0.        ]]

 ...

 [[428.           0.56597222   0.        ]
  [494.           0.56597222   0.        ]
  [369.           0.56597222   0.        ]
  ...
  [315.           0.56597222   0.        ]
  [416.           

In [1]:
#看一眼"x_offsets" "y_offsets"内部是什么

import numpy as np

data = np.load("PEMS08/test.npz")

x_offsets = data["x_offsets"]
y_offsets = data["y_offsets"]

print("x_offsets shape:", x_offsets.shape)
print("y_offsets shape:", y_offsets.shape)

print("\nRaw x_offsets:\n", x_offsets)
print("\nRaw y_offsets:\n", y_offsets)

# 转成一维方便看
print("\nFlattened:")
print("x_offsets:", x_offsets.flatten())
print("y_offsets:", y_offsets.flatten())

x_offsets shape: (12, 1)
y_offsets shape: (12, 1)

Raw x_offsets:
 [[-11]
 [-10]
 [ -9]
 [ -8]
 [ -7]
 [ -6]
 [ -5]
 [ -4]
 [ -3]
 [ -2]
 [ -1]
 [  0]]

Raw y_offsets:
 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]

Flattened:
x_offsets: [-11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0]
y_offsets: [ 1  2  3  4  5  6  7  8  9 10 11 12]


## 观察train

In [4]:
import numpy as np

data = np.load("PEMS08/train.npz")

print(data.files)

for key in data.files:
    arr = data[key]
    print(f"Key: {key}")
    print(f"  Shape: {arr.shape}")
    print(f"  Dtype: {arr.dtype}")
    print("-" * 40)


key = data.files[0]
arr = data[key]

print(arr[0])          # 第一个样本
print(arr[0].shape)    # 再确认一次维度




['x', 'y', 'x_offsets', 'y_offsets']
Key: x
  Shape: (10699, 12, 170, 3)
  Dtype: float64
----------------------------------------
Key: y
  Shape: (10699, 12, 170, 1)
  Dtype: float64
----------------------------------------
Key: x_offsets
  Shape: (12, 1)
  Dtype: int64
----------------------------------------
Key: y_offsets
  Shape: (12, 1)
  Dtype: int64
----------------------------------------
[[[1.33000000e+02 0.00000000e+00 0.00000000e+00]
  [2.10000000e+02 0.00000000e+00 0.00000000e+00]
  [1.24000000e+02 0.00000000e+00 0.00000000e+00]
  ...
  [7.40000000e+01 0.00000000e+00 0.00000000e+00]
  [9.40000000e+01 0.00000000e+00 0.00000000e+00]
  [6.00000000e+00 0.00000000e+00 0.00000000e+00]]

 [[1.14000000e+02 3.47222222e-03 0.00000000e+00]
  [1.85000000e+02 3.47222222e-03 0.00000000e+00]
  [1.19000000e+02 3.47222222e-03 0.00000000e+00]
  ...
  [7.30000000e+01 3.47222222e-03 0.00000000e+00]
  [8.40000000e+01 3.47222222e-03 0.00000000e+00]
  [4.00000000e+00 3.47222222e-03 0.00000000e+0

## 观察val

In [2]:
import numpy as np

data = np.load("PEMS08/val.npz")

print(data.files)

for key in data.files:
    arr = data[key]
    print(f"Key: {key}")
    print(f"  Shape: {arr.shape}")
    print(f"  Dtype: {arr.dtype}")
    print("-" * 40)


key = data.files[0]
arr = data[key]

print(arr[0])          # 第一个样本
print(arr[0].shape)    # 再确认一次维度




['x', 'y', 'x_offsets', 'y_offsets']
Key: x
  Shape: (3567, 12, 170, 3)
  Dtype: float64
----------------------------------------
Key: y
  Shape: (3567, 12, 170, 1)
  Dtype: float64
----------------------------------------
Key: x_offsets
  Shape: (12, 1)
  Dtype: int64
----------------------------------------
Key: y_offsets
  Shape: (12, 1)
  Dtype: int64
----------------------------------------
[[[ 75.           0.14930556   2.        ]
  [ 87.           0.14930556   2.        ]
  [123.           0.14930556   2.        ]
  ...
  [ 18.           0.14930556   2.        ]
  [ 52.           0.14930556   2.        ]
  [  0.           0.14930556   2.        ]]

 [[ 91.           0.15277778   2.        ]
  [108.           0.15277778   2.        ]
  [112.           0.15277778   2.        ]
  ...
  [ 17.           0.15277778   2.        ]
  [ 58.           0.15277778   2.        ]
  [  1.           0.15277778   2.        ]]

 [[ 65.           0.15625      2.        ]
  [ 82.           0.15625 

train: 10699
test: 3567
val: 3567